### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by HectorCastelli** [GIBIS-UNIFESP/wiRedPanda#5]
## TO-DO List
- [x] Add `.panda` to files when saving.  [link](https://github.com/lellisls/wiRedPanda/issues/10)
- [x] Undo/Redo. [link](https://github.com/lellisls/wiRedPanda/issues/1)
- [x] Boxes.  [link](https://github.com/lellisls/wiRedPanda/issues/9)
- [ ] QtInstaller. [link](https://github.com/lellisls/wiRedPanda/issues/3)
- [ ] Add keyboard shortcuts to inputs. [link](https://github.com/lellisls/wiRedPanda/issues/11)
- [ ] Line Split.
- [ ] Zoom.
- [ ] Scene-Auto zoom.
- [x] Align to grid [link](https://github.com/lellisls/wiRedPanda/issues/14).
- [ ] Align lines to grid (?)
- [ ] Hide Lines, Wires and Ports.
- [ ] Show Lines with issues.
- [x] Search.
- [ ] Flip Elements in the latteral pannel.
- [ ] 16-seg Display.
- [ ] Allow ports with more than 8 in/out.
- [ ] Labels always in horizontal.
- [ ] Verify if file changed outside.
- [ ] MUX and DEMUX.
- [ ] Ctrl + Drag copy.
- [ ] Lauch in new instance.
