### ISSUE TITLE
Bug List

### ISSUE THREAD

**Issue by HectorCastelli** [GIBIS-UNIFESP/wiRedPanda#6]
- [ ] Problems with latches [link](https://github.com/lellisls/wiRedPanda/issues/4)
- [x] Drag wire to Element Pannel causes freezing [link](https://github.com/lellisls/wiRedPanda/issues/2)
- [x] Scroll doesn't work with mouse middle button [link](https://github.com/lellisls/wiRedPanda/issues/15)
- [x] Slow rendering time
- [x] Control loss in draggin a single port or a group [link](https://github.com/lellisls/wiRedPanda/issues/17)
- [x] **[WIN]** Drag'n'Drop stops working [link](https://github.com/lellisls/wiRedPanda/issues/7)
