### ISSUE TITLE
ROADMAP

### ISSUE THREAD

**Issue by HectorCastelli** [GIBIS-UNIFESP/wiRedPanda#8]
## Features we have yet to implement
- [ ] Karnaught Map or Truth Table.
- [ ] Limited Clock Frequencies.
- [ ] Images as buttons.
- [ ] Labels as separate elements.
- [ ] Verilog Script Generator.
- [ ] Add support to custom image backgrounds..
- [ ] Add lines in empty ports.
- [ ] Create separate modules for execution and edition.
- [ ] Bugs and Warnings highlights.
