### ISSUE TITLE
Box

### ISSUE THREAD

**Issue by lellisls** [GIBIS-UNIFESP/wiRedPanda#9]
## Todo list:
- [x] Create Box's Graphic Element. [link](https://github.com/lellisls/wiRedPanda/commit/5edffaf531e9b4b90d11516d960e7572cf9ca343)
- [x] Box serialization. [link](https://github.com/lellisls/wiRedPanda/commit/5edffaf531e9b4b90d11516d960e7572cf9ca343)
- [x] Import files. [link](https://github.com/lellisls/wiRedPanda/commit/5edffaf531e9b4b90d11516d960e7572cf9ca343)
- [x] Circuit simulation. [link](https://github.com/lellisls/wiRedPanda/commit/5edffaf531e9b4b90d11516d960e7572cf9ca343)
- [x] Fix input/output labels.
- [x] ~~QNodes based graphic implementation.~~
- [x] Open linked circuit on double click.
- [ ] Embed circuits into file. 
- [x] Add boxes to the left menu after load a circuit.
- [x] Recent boxes list.
- [x] Alternatives to define i/o port positions. [link](https://github.com/lellisls/wiRedPanda/issues/12)
- [x] Default labels for i/o.
- [ ] ~~Propagate errors.~~
- [x] Relative path.
- [x] Error handling when a file link is lost.
- [x] Detect when the linked file is updated.

## Current version
![image](https://cloud.githubusercontent.com/assets/7882921/10476732/d69f39e4-7226-11e5-8857-cf3fb0b4532c.png)

## Older versions
![image](https://cloud.githubusercontent.com/assets/7882921/8555852/2c20474c-24c9-11e5-9a8b-07dd940aed80.png)

![captura_de_tela_de_2015-07-07_01-10-05](https://cloud.githubusercontent.com/assets/7882921/8546449/48ab0360-248e-11e5-8c38-148ccf3f3007.png)
